export const BAD_CREDENTIALS = 'BAD_CREDENTIALS';
export const NO_DATA = 'NO_DATA';

export const DEFAULT_TITLE = 'ARENA_SUNSET';
export const LS_STORAGE_PREFIX = '$-ARENA_SUNSET_LOCAL_STORAGE-';

export const LS_USERS = LS_STORAGE_PREFIX + 'USERS';
export const LS_TOKEN = LS_STORAGE_PREFIX + 'TOKEN';
export const LS_LOCALE = LS_STORAGE_PREFIX + 'LOCALE';
